version: '3.4'

services:
  dev4containerdjango:
    image: dev4containerdjango
    build:
      context: .
      args:
        - DEV=true
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
#   postgresdb:
#     image: postgres
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_DB=postgresdb
#       - POSTGRES_USER=dbuser
#       - POSTGRES_PASSWORD=changeme
# volumes:
#   pgdata: