version: '3.4'

services:
  dev4containerdjango:
    image: dev4containerdjango
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=postgresdb
      - DB_NAME=devdb
      - DB_USER=dbuser
      - DB_PASS=changeme
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeme
volumes:
  pgdata: